# Add configuration values here, as shown below.
#
# pusher_app_id: "2954"
# pusher_key: 7381a978f7dd7f9a1117
# pusher_secret: abdc3b896a0ffb85d373
# stripe_api_key: sk_test_2J0l093xOyW72XUYJHE4Dv2r
# stripe_publishable_key: pk_test_ro9jV5SNwGb1yYlQfzG17LHK
#
# production:
#   stripe_api_key: sk_live_EeHnL644i6zo4Iyq4v1KdV9H
#   stripe_publishable_key: pk_live_9lcthxpSIHbGwmdO941O1XVU

development:
  database_name: "api-test_development"
  database_user: "postgres"
  database_pass: "postgres123"
  database_host: "127.0.0.1"

  api_watson: "https://trashbot-node.herokuapp.com/api/message"

production:
  database_name: ""
  database_user: ""
  database_pass: ""
  database_host: ""

  api_watson: ""